create table if not exists public.listing_audit_logs (
  id bigint generated by default as identity primary key,
  listing_id uuid not null,
  operation text not null check (operation in ('INSERT', 'UPDATE', 'DELETE')),
  actor_id uuid,
  actor_role text not null,
  actor_email text,
  old_record jsonb,
  new_record jsonb,
  changed_at timestamptz not null default now()
);

create index if not exists listing_audit_logs_listing_changed_idx
  on public.listing_audit_logs (listing_id, changed_at desc);

create index if not exists listing_audit_logs_actor_changed_idx
  on public.listing_audit_logs (actor_id, changed_at desc)
  where actor_id is not null;

comment on table public.listing_audit_logs is
  'Database-generated immutable audit trail for every listing write.';

create or replace function public.audit_listing_write()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  previous_row jsonb;
  current_row jsonb;
begin
  previous_row := case when tg_op in ('UPDATE', 'DELETE') then to_jsonb(old) else null end;
  current_row := case when tg_op in ('INSERT', 'UPDATE') then to_jsonb(new) else null end;

  insert into public.listing_audit_logs (
    listing_id,
    operation,
    actor_id,
    actor_role,
    actor_email,
    old_record,
    new_record
  ) values (
    coalesce(new.id, old.id),
    tg_op,
    auth.uid(),
    coalesce(auth.role(), current_user),
    auth.jwt() ->> 'email',
    previous_row,
    current_row
  );

  return coalesce(new, old);
end;
$$;

drop trigger if exists listings_audit_writes on public.listings;
create trigger listings_audit_writes
  after insert or update or delete on public.listings
  for each row execute function public.audit_listing_write();

alter table public.listing_audit_logs enable row level security;

drop policy if exists listing_audit_logs_authenticated_read on public.listing_audit_logs;
create policy listing_audit_logs_authenticated_read
  on public.listing_audit_logs for select to authenticated
  using (true);

revoke insert, update, delete, truncate on public.listing_audit_logs from public, anon, authenticated;
