-- First migration managed by Supabase CLI; see supabase/MIGRATIONS.md.
create table if not exists public.listing_price_history (
  id bigint generated by default as identity primary key,
  listing_id uuid not null references public.listings(id) on delete cascade,
  price numeric,
  currency text,
  recorded_at timestamptz not null default now()
);

create index if not exists listing_price_history_listing_recorded_idx
  on public.listing_price_history (listing_id, recorded_at desc);

comment on table public.listing_price_history is
  'Append-only history of initial and changed listing prices observed by Vatrio.';

create or replace function public.record_listing_price_history()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT'
     or old.price is distinct from new.price
     or old.currency is distinct from new.currency then
    insert into public.listing_price_history (listing_id, price, currency)
    values (new.id, new.price, new.currency);
  end if;
  return new;
end;
$$;

drop trigger if exists listings_record_price_history on public.listings;
create trigger listings_record_price_history
  after insert or update of price, currency on public.listings
  for each row execute function public.record_listing_price_history();

insert into public.listing_price_history (listing_id, price, currency, recorded_at)
select listing.id, listing.price, listing.currency, coalesce(listing.date_scraped, now())
from public.listings as listing
where not exists (
  select 1
  from public.listing_price_history as history
  where history.listing_id = listing.id
);
